### ISSUE TITLE
The image_id values in CC3M do not match the original CC3M

### ISSUE THREAD

**Issue by fakhralwajih** [google/crossmodal-3600#2]
The image_id values in CC3M do not match the original CC3M. Additionally, in COCO, some image_id values are not found in either coco2014 or coco2017."

**Comment by jponttuset** [comment]
Hi @fakhralwajih,
We're working on publishing this mapping. Apologies for the delay.

**Comment by floschne** [comment]
@jponttuset , is there any update :) ?

**Comment by jponttuset** [comment]
Hi @floschne and @fakhralwajih,

Apologies for the delay again. We've now fixed the issue.
Please let us know if you still find problems with the data, or the opposite too, if you check the data and can finally use it.

Best,

**Comment by floschne** [comment]
@jponttuset thank you very much :) I'll have a look into the data in the coming days!
