### ISSUE TITLE
Question regarding the `image_id` in the machine translated training data

### ISSUE THREAD

**Issue by floschne** [google/crossmodal-3600#3]
Hi, thanks for creating and sharing this dataset!

I have a question regarding the `image_id` in the machine translated training data. 

As far as I can tell, the `image_id` field does not match the original data that can be downloaded here: https://ai.google.com/research/ConceptualCaptions/download

Can you please provide the correct mapping between the `image_id` provided here and the original data (both for CC3M and COCO) ?

**Comment by jponttuset** [comment]
Hi @floschne,
We're working on publishing this mapping. Apologies for the delay.

**Comment by floschne** [comment]
Thank you!
